.gitignore, Jobs/PrGate.yml, Jobs/Python/RunDevTests.yml, LICENSE.txt, README.md, ReadMe.rst, RepoDetails.md, Steps/BuildBaseTools.yml, Steps/BuildPlatform.yml, Steps/FetchGitHubFile.yml, Steps/InstallMarkdownLint.yml, Steps/InstallSpellCheck.yml, Steps/PrGate.yml, Steps/Python/RunFlake8Tests.yml, Steps/Python/RunPytest.yml, Steps/RunMarkdownLint.yml, Steps/RunPatchCheck.yml, Steps/RunSpellCheck.yml, Steps/SetNodeVersion.yml, Steps/SetupPythonPreReqs.yml
This adds starting content for the Mu Developer Operations (DevOps)
repo.
This repo (at least at this time) is primarily composed of Azure
Pipelines YAML files used as common resources between many Project
Mu repositories.
Repos are intended to bind against a source repository at pipeline
build time to expose the templates used for the build.
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#define-a-repositories-resource
Each "leaf" YAML file (the YAML file used in the actual pipeline) is
expected to define a repository resource onto this repo and include
the appropriate top-level template file.
Typically, this is:
- Jobs/PrGate.yml
- Steps/BuildPlatform.yml
Each template provides parameter customization for common config
points of …
=> Add initial content

Steps/PrGate.yml
Adds a condition to build steps to only execute if pkg_count is
greater than zero. The pkg_count is set to a default value of 1.
Stuart PR Eval might set it to zero if that is used and no packages
need to be built. When it does so, it also clears the package name
variable. So not only is the a performance optimization, it is
required if Stuart PR Eval runs and determines no packages need
to be built.
=> Steps/PrGate.yml: Add pkg_count condition to build steps

Jobs/PrGate.yml, Steps/PrGate.yml
Allow repos using the templates to opt out of PR evaluation.
The default is to perform PR eval for backward compatibility with
current users.
=> PrGate.yml: Add do_pr_eval template parameter

Jobs/PrGate.yml
Passes the value given to the job template (from the platform YAML
file) to the Steps/PrGate.yml template file.
=> Jobs/PrGate.yml: Pass do_pr_eval value to step template

.github/workflows/CodeQl.yml
Adds a new workflow YAML file that can be reused by repos that need
to run CodeQL.
The workflow accepts the following input strings:
- setup_command - The (Stuart) setup command to run
- update_command - The (Stuart) update command to run
- build_command - The (Stuart) build command to run
- python_version - The Python version to use
The command strings can be an empty string to skip that command.
The default Python version is currently '3.x'.
This reusable workflow encapsulates common CodeQL pre and post
build steps and centralizes default values for common configuration
points like the Python version to use for CodeQL workflows.
=> Add CodeQL reusable GitHub workflow

Notebooks/MyPullRequests.github-issues, Notebooks/PullRequests.github-issues, Notebooks/ReadMe.md
Adds github-issues notebooks that present a dashboard of Project Mu
status. These can be opened in VS Code using the "GitHub Issue
Notebooks" extension. By extension, they can also be opened using the
VS Code web interface to view in a Web browser.
For more information, see the Notebooks/ReadMe.md file.
Dashboard Examples:
.   .   .
.   .   .
=> Add Project Mu status notebooks

Steps/ApplyAdoBranchNameWorkaround.yml, Steps/BuildPlatform.yml, Steps/PrGate.yml
Moves workaround logic for branch names on ADO to a dedicated file
so it can be shared between other templates.
=> ApplyAdoBranchNameWorkaround.yml: Add file

Steps/ApplyAdoBranchNameWorkaround.yml
Commit d6d4f56 introduced an error during conflict resolution that
adds an extra "condition" member to the powershell step.
The extra line is removed in this change.
=> Steps/ApplyAdoBranchNameWorkaround.yml: Fix error from conflict resolution

Steps/PrGate.yml
Allows YAML files to pass extra install steps to take place before
build. This exactly matches the parameter currently in
Steps/BuildPlatform.yml and provides consistency in the parameter
interface between these two files.
=> Steps/PrGate.yml: Add extra install step parameter

Steps/PrGate.yml
Introduces a new parameter called "extra_build_args" that can be used
to specify additional flags to pass to build commands.
This is used to pass flags needed to generate code coverage results
in this change.
The coverage.xml and coverage.html files added to the log copy step
will not have an impact if code coverage is not enabled.
For now, the code coverage publication step depends on the platform
setting "CODE_COVERAGE=TRUE" in the "extra_build_args" parameter.
This can be refactored/generalized as needed in the future.
=> PrGate.yml: Add support for publishing code coverage results

Jobs/PrGate.yml, Jobs/Python/RunDevTests.yml
Removes parameterized input from job names so the name is not
dependent on variable resolution.
=> Simplify job names

Steps/BuildPlatform.yml, Steps/PrGate.yml
Before:
##vso[task.setvariable variable=pkg_count;isOutpout=true]{pkgcount}
After ("isOutpout" to "isOutput"):
##vso[task.setvariable variable=pkg_count;isOutput=true]{pkgcount}
=> Fix PR Eval typo (present since 201911)

Steps/BuildPlatform.yml, Steps/PrGate.yml
Since "isOutput" was previously spelled incorrectly (see d326659), the resulting
behavior was equivalent to "isOutput" not being specified at all.
Subsequent code has been written such that it refers to the variable
as a variable set in the same job rather than a multi-job variable as
"isOutput" is used for - the code simply refers to the variable name
rather than \<step\>.\<var name\>.
This change simply removes "isOutput" so the original set of code
assumptions continue to work as before.
=> Update code to align with previous isOutput bug behavior

Jobs/PrGate.yml, Steps/SetupPythonPreReqs.yml
Moves pip installation behavior back to what was done before
5f3c041. After analyzing several options, including using virtual
environments, this is the path that most consistently and simply
works for container and non-container builds.
It could potentially be built upon in the future, but it gets all of
the builds functional for now.
Resolves the following warning currently issued by Linux build
agents since 5f3c041 was committed:
"WARNING: Running pip as the 'root' user can result in broken
permissions and conflicting behaviour with the system package
manager.
It is recommended to use a virtual environment instead:
https://pip.pypa.io/warnings/venv"
=> Revert container updates in 5f3c041

Jobs/PrGate.yml
Switch to using a boolean indicating a container build for the PrGate job. This allows a centralized location for the container image used for all devops rather than needing to be updated across the consuming repos.
=> Switch to simple boolean for using container build

Steps/SetupPythonPreReqs.yml
Fixes #26 
Currently pip installation gives the following deprecation warnings:
```
DEPRECATION: future is being installed using the legacy
'setup.py install' method, because it does not have a
'pyproject.toml' and the 'wheel' package is not installed.
pip 23.1 will enforce this behaviour change. A possible
replacement is to enable the '--use-pep517' option.
Discussion can be found at https://github.com/pypa/pip/issues/8559
Running setup.py install for future: started
Running setup.py install for future: finished with status 'done'
DEPRECATION: pefile is being installed using the legacy
'setup.py install' method, because it does not have a
'pyproject.toml' and the 'wheel' package is not installed.
pip 23.1 will enforce this behaviour change. A possible
replacement is to enable the …
```
=> SetupPythonPreReqs.yml: Upgrade pip and install wheel and setuptools

.github/workflows/Stale.yml
Adds a new workflow YAML file that can be reused by repos that need
to check for stale issues and pull requests (PRs).
The workflow accepts the following input values:
- `days-before-issue-stale` - Days before an issue is stale
- default: 45
- `days-before-pr-stale` - Days before a PR is stale
- default: 60
- `days-before-issue-close` - Days before a stale issue is closed
- default: 7
- `days-before-pr-close` - Days before a stale PR is closed
- default: 7
- `stale-issue-message` - Comment made on stale issues
- default:
"This issue has been automatically marked as stale because it
has not had activity in 45 days. It will be closed if no
further activity occurs within 7 days. Thank you for your
contributions."
- `stale-pr-message` - Comment made on stale PRs
- default:
"This PR has been …
=> Add reusable Stale GitHub workflow

.github/Labels.yml, .github/workflows/LabelSyncer.yml
Add reusable GitHub Label Sync workflow
Adds a new workflow and accompanying manifest that specifies labels
used in Project Mu to control label management from this centralized
repository.
- `.github/Labels.yml` - Centralized label manifest for Project Mu
- `.github/workflows/LabelSyncer.yml` - Single GitHub Action to apply
labels in the label manifest to all Project Mu repos that call the
workflow.
Repos are expected to to sync labels by calling `LabelSyncer.yml`
on a roughly consistent cadence across Project Mu.
Repos can pass a repo-specific config as an input to this reusable
workflow.
This has the benefit of reducing developer time working with labels
but more importantly makes labels consistent across Project Mu repos
and tracks changes to labels in Mu DevOps source history. …
=> Add reusable GitHub Label Sync workflow

.github/workflows/FileSyncer.yml
`TEAM_REVIEWERS` needs to include the organization with the team
name so "microsoft/project-mu-dependency-reviewers" instead of
"project-mu-dependency-reviewers".
=> FileSyncer.yml: Add microsoft prefix to review team

.sync/github_templates/contributing/CONTRIBUTING.md
Resolve the following markdownlint issue:
```
CONTRIBUTING.md:35:121 MD013/line-length Line length
[Expected: 120; Actual: 210]
```
=> CONTRIBUTING.md: Fix long line for markdownlint

.sync/Files.yml, .sync/ci_config/.markdownlint.yaml
The file sync process can compile files as Nunjucks[1] templates if
the `template` field is present. In this case, allowed HTML elements
in markdown files are adjusted for the following repos:
- The mu (documentation) repo to allow `<center>` and `<img>`
tags.
- The mu_feature_mm_supv repo to allow `<SmmCategory>` and
`<PolicyAccessAttribute>` tags.
[1] https://mozilla.github.io/nunjucks/
=> .sync/markdownlint.yaml: Templatize allowed HTML elements

.sync/ci_config/.markdownlint.yaml
The text already comes with braces, so they are not needed explicitly
in the YAML config file.
=> .sync/markdownlint.yaml: Update brace syntax

.github/Labels.yml, .github/ReleaseDraft.yml, .github/workflows/ReleaseDrafter.yml, .sync/Files.yml, .sync/workflows/leaf/release-draft.yml, ReadMe.rst
Closes #50
Adds a new workflow and accompanying configuration files that allow
releases to automatically be drafted in repos as pull requests are
completed.
Semantic versioning is automatically determined based on the standard
set of Project Mu labels associated with the pull request.
The types of changes (e.g. bug fix, new feature, etc.) are
automatically categorized in the pull request based on the labels as
well.
This makes tracking the new Semantic Version based on the type of
changes automatic and a release is always ready. In between releases,
the draft is a nice way to see a high-level delta since the last
release.
- `.github/ReleaseDrafter.yml` - Single reusable workflow to maintain
a release draft as pull requests complete.
- `.github/ReleaseDraft.yml` - Configuration file for …
=> Add Semantic Versioning Release workflow [Rebase & FF]

.sync/workflows/config/label-issues/regex-pull-requests.yml
Fixes #47 
The checkbox exposed to contributors in a PR to determine whether
the PR has a functional impact states:
"Impacts functionality?"
This uses positive logic to simplify understanding by the user.
Currently the `impact:non-functional` label is applied if the
checkbox is checked.
This change inverts the logic to apply the label as expected.
=> label-issues: Invert functional impact label logic

Steps/InstallMarkdownLint.yml
Updates to the latest markdownlint-cli to stay current. 0.31.1 was released
on 2/9/2022 per the version history:
https://www.npmjs.com/package/markdownlint-cli
Note: 0.32 introduces new failures in some repos that would need to be
addressed before moving to 0.32.x. 0.32.2 was specifically tested.
=> InstallMarkdownLint.yml: Update to markdownlint-cli 0.31.1

.sync/azure_pipelines/matrix_dependent/Ubuntu-CLANGPDB.yml, .sync/azure_pipelines/matrix_dependent/Windows-CLANGPDB.yml
After this change:
- `Ubuntu-CLANGPDB.yml`
- Uses: `tool-chain-clangpdb-ubuntu-vm-image`
- `Windows-CLANGPDB.yml`
- Uses: `tool-chain-clangpdb-windows-vm-image`
These were previously reversed.
=> .sync/azure-pipelines: Swap CLANGPDB VM image name

.github/Labels.yml, .github/workflows/IssueTriager.yml, .sync/Files.yml, .sync/workflows/config/triage-issues/advanced-issue-labeler.yml, .sync/workflows/leaf/triage-issues.yml, ReadMe.rst
Closes #54 
Adds a new workflow and accompanying configuration files that
apply labels to new issues based on options chosen by the submitter
in an issue form.
- `.github/IssueTriager.yml` - Single reusable workflow to apply
labels to issues based on user input in issue forms.
- `.sync/workflows/config/triage-issues/advanced-issue-labeler.yml` -
Configures how labels are applied to issues based on issue form
input.
- `.sync/workflows/leaf/triage-issues.yml` - A leaf workflow that can
be synced to repos to trigger the reusable workflow in Mu DevOps.
This change also enables file syncing of this action to all repos
that issue forms are currently being synced to.
=> Add Issue Triage workflow

.github/workflows/AutoMerger.yml, .sync/Files.yml, .sync/workflows/leaf/auto-merge.yml, ReadMe.rst
Adds a new workflow that automatically merges pull requests in
Project Mu repos under certain conditions.
As automated bots pick up mundane tasks like syncing PIP module
updates, submodules, files, and so on, an increasing number of
pull requests can accumulate that essentially update dependencies
we expect to be updated over time. In most cases, we simply care
that the new update passes CI checks.
This workflow is currently configured to automerge dependabot and
uefibot pull requests.
Files added:
- `.github/workflows/AutoMerger.yml` - Reusable workflow to auto
merge pull requests that meet given criteria.
- `.sync/workflows/leaf/auto-merge.yml` - Leaf workflow file to
auto merge pull requests in a given repo.
=> Add reusable Auto Merge workflow

.sync/Files.yml, .sync/workflows/leaf/auto-merge.yml, .sync/workflows/leaf/release-draft.yml, .sync/workflows/leaf/triage-issues.yml
When some workflows were added recently, the reusable workflow file
that the leaf files depend on in mu_devops did not exist yet.
Therefore, those leaf files depended on the `main` branch instead
of a mu_devops release tag as the files would be in the `main`
branch as soon as the PR was merged.
Now that all of the reusable workflows are in a tagged release
(as of the `v1.3.0` release), this change sets them to a fixed version
of Mu DevOps as well.
=> .sync: Set recent workflows to a fixed version of mu_devops

.sync/workflows/config/label-issues/file-paths.yml, .sync/workflows/config/label-issues/regex-pull-requests.yml, .sync/workflows/config/triage-issues/advanced-issue-labeler.yml
These files were added without the notice in the copyright area that
states the files should be updated in mu_devops.
This change adds the notice.
=> .sync/workflows: Add file sync notice to some files

.sync/github_templates/contributing/CONTRIBUTING.md, .sync/github_templates/pull_requests/pull_request_template.md
Adds pull request best practices to CONTRIBUTING.md and references this document + pull request best practices in the pull_request_template.md so all contributors are confronted with this guide before they open a pull request rather than afterward by the bot.
TODO:
=> Add pull-request best practices guide

.github/workflows/AutoMerger.yml, .sync/workflows/leaf/auto-merge.yml
The auto merge process needs two reviews to meet Project Mu branch
protection policy requirements. This change auto approves dependency
update pull requests so they can be auto merged.
=> Add auto approval for auto merge

.github/dependabot.yml, .github/workflows/AutoApprover.yml, .github/workflows/AutoMerger.yml, .github/workflows/FileSyncer.yml, .sync/Version.njk, .sync/workflows/leaf/auto-approve.yml
Split approval and merge workflows
Splitting the workflows provides several benefits:
1. Simplifies logic due to jobs being attached to separate triggers
relevant for the specific job.
2. Reduces number of status checks shown in PRs due to certain steps
being skipped in irrelevant circumstances.
3. Allows better workflow reuse.
The reviewers are also dropped from dependabot PRs since the pending
team reviewer is (1) not acted upon (2) can delay PR merging if the
reviewer team has not reviewed the PR.
The version is updated in anticipation of this change. It will be
modified if the expected version changes before this PR is merged.
=> Split approval and merge workflows

.sync/dependabot/actions-pip-submodules.yml, .sync/dependabot/actions-pip.yml
Removes the microsoft/project-mu-dependency-reviewers team from
reviews to reduce messages with the automated workflow.
=> .sync/dependabot: Remove team reviewers

Notebooks/OpenIssues.github-issues, Notebooks/PullRequests.github-issues, Notebooks/ReadMe.md
Added a issue triage dashboard that enables queries for no assignee and no labels
=> Add dashboard for issue triage

Steps/BuildPlatform.yml
Updates the template to allow the platform to specify a custom
timeout for running to shell.
The previous value of `5` is the default.
=> Steps/BuildPlatform.yml: Add Run to Shell timeout parameter

Notebooks/ReadMe.md
The links in Readme.md (the second and third) were to the individual files in the repo, instead of github.dev, which enables quick access to run the queries.
Changed the Dashboards for Personal Issues to use github.dev.
=> Changed links to github.dev instead of github.com

.github/workflows/AutoMerger.yml
Closes #82 
Increase the merge and update timeouts to increase likelihood the
operations can occur.
=> .github/workflows/AutoMerger.yml: Increase timeouts

.sync/github_templates/ISSUE_TEMPLATE/bug_report.yml, .sync/github_templates/ISSUE_TEMPLATE/documentation_request.yml, .sync/github_templates/ISSUE_TEMPLATE/feature_request.yml, .sync/workflows/config/triage-issues/advanced-issue-labeler.yml
Closes #85 
Adds a new selection to issues to request maintainer feedback.
The default is no maintainer feedback is necessary. Opting for
maintainer feedback adds the `state:needs-maintainer-feedback`
label to the issue.
=> Add ability to request maintainer feedback in issues

.sync/Files.yml, .sync/workflows/leaf/scheduled-maintenance.yml
Closes #33 
Adds a workflow to prune issues and pull requests marked as
"won't fix" (via the label `state:wont-fix`).
The workflow is scheduled to run every hour. The minimum event
schedule granularity for GitHub is every 5 minutes.
=> Add scheduled maintenance workflow

.sync/Files.yml, Notebooks/MyPullRequests.github-issues, Notebooks/OpenIssues.github-issues, Notebooks/PullRequests.github-issues
Closes #94 
1. Syncs files to https://github.com/microsoft/mu_feature_dfci
2. Adds issues and pull requests in mu_feature_dfci to the GitHub
issues notebooks
=> Add support for the mu_feature_dfci repo

.github/workflows/FileSyncer.yml, .sync/dependabot/actions-pip-submodules.yml, .sync/dependabot/actions-pip.yml
Closes #100 
File sync can cause a large impact on CI resources. This change moves
the trigger to a schedule outside office hours (1AM Pacific Time /
9AM UTC daily) to reduce resource usage during most active periods
of other development.
Schedules dependabot checks for times outside normal Pacific
timezone working hours when most development occurs.
=> Dependabot and FileSyncer: Run after hours

.sync/Version.njk, Jobs/PrGate.yml
Includes the changes noted in the following comparison from the prior
container image (`5800d58`):
https://github.com/tianocore/containers/compare/5800d58..5b8a008
=> Update Fedora 35 Build container image to 5b8a008

.sync/azure_pipelines/custom/mu_feature_config/Ubuntu-GCC5.yml, .sync/azure_pipelines/custom/mu_feature_config/Windows-VS.yml, .sync/azure_pipelines/custom/mu_feature_ipmi/Ubuntu-GCC5.yml, .sync/azure_pipelines/custom/mu_feature_ipmi/Windows-VS.yml, .sync/azure_pipelines/custom/mu_feature_mm_supv/Ubuntu-GCC5.yml, .sync/azure_pipelines/custom/mu_feature_mm_supv/Windows-VS.yml
Feature repos are being moved to use ci_setup's GetDependencies() instead of external dependencies. Due to this, ci_setup is required.
=> .sync/azure_pipelines: Enable ci_setup in feature repos

.sync/Files.yml
Adds automated release drafting to the following repos:
- microsoft/mu_crypto_release
- microsoft/mu_feature_config
- microsoft/mu_feature_dfci
- microsoft/mu_feature_ipmi
- microsoft/mu_feature_mm_supv
- microsoft/mu_feature_uefi_variable
- microsoft/mu_tiano_platforms
This was previously piloted in mu_devops.
=> .sync/Files.yml: Sync release drafter to feature and platform repos

Jobs/CreateBuildMatrix.yml, Jobs/PrGate.yml, Steps/BinaryCopyAndPublish.yml, Steps/BuildBaseTools.yml, Steps/BuildPlatform.yml, Steps/CommonLogCopyAndPublish.yml, Steps/NuGet.yml, Steps/OtherCopyAndPublish.yml, Steps/PrGate.yml, Steps/SetupPythonPreReqs.yml
Introduces the ability to publish NuGet package releases from
Project Mu repos.
Also includes changes to publish artifacts by type to more cleanly
control how they are produced & consumed - binaries, logs, and other.
**Integration Notes**
This commit updates the major version of mu_devops. This means it
might require integration work that will result in a repo build
breaking unless performed.
- Artifacts are now published under three separate categories of "binaries",
- "logs", and "other"
- Previously all artifacts were published under `"Build Logs $(System.JobName)"`
- Any flows dependent on artifact names will need to be updated
- Three new templates are provided for reusable publishing of content in these categories:
1. `Steps/BinaryCopyAndPublish.yml`
2. …
=> Add NuGet publishing

.sync/github_templates/security/SECURITY.md
The following errors were raised in https://github.com/microsoft/mu
and resolved in this change:
- SECURITY.md:11 MD012/no-multiple-blanks Multiple consecutive blank lines
[Expected: 1; Actual: 2]
- SECURITY.md:22:84 MD009/no-trailing-spaces Trailing spaces
[Expected: 0 or 2; Actual: 1]
- SECURITY.md:34 MD012/no-multiple-blanks Multiple consecutive blank lines
[Expected: 1; Actual: 2]
=> .sync/SECURITY.md: Fix markdownlint errors

.github/workflows/Labeler.yml
Reverts commit 6678c19
This update is causing failures to be returned from the action
due to attempting to remove labels that do not exist.
Make an update plan separately and update in the future.
=> Revert "GitHub Action: Bump github/issue-labeler from 2.5 to 2.6 (#98)"

Steps/BuildPlatform.yml, Steps/PrGate.yml
Adds a work-around to the naming provided by System.PullRequest.targetBranch on ADO repos by stripping the refs/heads/ from the path since that makes it unrecognizable to git for the git diff used by stuart_pr_eval.
=> Re-introduce workaround to fix ADO path names for PR eval

.github/release-draft-config.yml, .github/workflows/ReleaseDrafter.yml, .github/workflows/release-draft.yml, .sync/Files.yml, .sync/Version.njk, .sync/workflows/config/release-draft/release-draft-config.yml, .sync/workflows/leaf/release-draft.yml, ReadMe.rst
Fixes #108
Commit 6e00a3d added file sync for the release drafter flow to
Project Mu platform and feature repos. However, the config file
used by the workflow must be local to the repo, so it needs to
be synced as well.
This change syncs the config file.
=> .sync/Files.yml: Sync release drafter config file

.github/workflows/release-draft.yml, .sync/Version.njk
https://github.com/microsoft/mu_devops/compare/v1.7.4...v2.0.1
General release Info: https://github.com/microsoft/mu_devops/releases
An important change in this release is reverting the label workflow
from v2.6 to v2.5 to resolve a regression:
https://github.com/microsoft/mu_devops/pull/110
=> .sync/Version.njk: Update Mu repos to Mu DevOps v2.0.1

.sync/azure_pipelines/custom/mu_feature_config/Ubuntu-GCC5.yml, .sync/azure_pipelines/custom/mu_oem_sample/Ubuntu-GCC5.yml, .sync/azure_pipelines/matrix_dependent/Ubuntu-GCC5.yml
The following commit in tianocore/containers switched from `microdnf`
to `dnf` since `microdnf` is no longer available in the Fedora 35
minimal base image.
https://github.com/tianocore/containers/commit/3487a34
Therefore, `microdnf` will currently fail (not found). This change
updates code using the Fedora 35 container image to switch to `dnf`.
=> .sync/azure_pipelines: Switch from microdnf to dnf

.sync/workflows/config/release-draft/release-draft-config.yml
Closes #119 
Breaking changes are identified with the GitHub label:
`impact:breaking-change`
Prior to this change, that label rolled the major version of the
repo.
Now, the label also places corresponding changes into a "Breaking
Changes" section of the release notes so it is easy for consumers
to see breaking changes in a release.
=> release-draft-config.yml: Add breaking changes section

.sync/github_templates/ISSUE_TEMPLATE/config.yml
In the "new" issues menu there was a link for Microsoft's Security Policy.   This is no longer accurate and now each repo has been updated with a valid SECURITY.MD file.
=> Remove link to Microsoft security policy for Project Mu repos

.sync/dependabot/actions-pip-submodules.yml, .sync/dependabot/actions-pip.yml
The version is centrally managed in mu_devops and pushed to other
repos in file syncs. Therefore, dependabot does not need to manage
the version independently in respective repos.
=> .sync/dependabot: Do not update microsoft/mu_devops in Actions updates

.sync/Files.yml, .sync/workflows/leaf/codeql.yml
Adds a new workflow that is synced to Mu repos that are
currently expected to run against CodeQL.
This workflow has the following features to support
maintainability across the repos it is synced to:
- The packages are auto discovered and a dynamic matrix
is generated for each package build. This allows the
same file to work as-is in each repo that performs
CI builds (packages are in the repo root directory).
- The Mu Basecore plugin directory is auto discovered
in the workspace based on the presence of the CodeQL
plugin being present in the directory.
- The operations supported by the Stuart CI script are
dynamically discovered.
- CodeQL is only run on Windows agents. There is a known
issue when building edk2-style code on Linux so this
avoids encountering that issue.
See: …
=> .sync: Add CodeQL GitHub workflow

.sync/workflows/leaf/codeql.yml
Some repos that use the workflow have a `main` branch instead of a
`release` branch as their primary branch.
=> .sync: Add main branch as a trigger to CodeQL workflow

.sync/workflows/config/release-draft/release-draft-config.yml
Dependabot is noisier now than it used to be, exclude it from release
notes to focus on important changes.
=> .sync/release-draft-config.yml: Exclude dependabot contributions

.sync/workflows/leaf/codeql.yml
It is a well known limitation that GitHub uses the pattern
`<install_dir>/_work/<repo_name>/<repo_name>/` as the working
directory on the GitHub workflow agents.
It is redundant and particularly impactful on Windows as discussed
below:
https://github.com/msysgit/msysgit/wiki/Git-cannot-create-a-file-or-directory-with-a-long-path
This especially causes an issue in a Mu repository at the moment
(`mu_common_intel_min_platform`) due to its longer name which is
repeated twice in the path (as `<repo-name>`).
This change is limited to the GitHub CodeQL workflow and was found
to resolve the issue encountered and not raise any additional issues
in this workflow in testing.
=> .sync/codeql.yml: Use Git long paths on Windows

Notebooks/MyPullRequests.github-issues, Notebooks/OpenIssues.github-issues, Notebooks/PullRequests.github-issues
Fixes repo name typo so results are returned from the repo.
=> Notebooks: Fix mu_silicon_arm_tiano repo name typo

.sync/Files.yml
Syncs the CodeQL leaf workflow to the following additional repos:
- microsoft/mu_feature_config
- microsoft/mu_feature_ipmi
- microsoft/mu_oem_sample
- microsoft/mu_silicon_arm_tiano
The workflow is now synced to all Mu repos with large amounts of
C code except mu_tiano_platforms. That will be included in a
future change.
=> .sync/Files.yml: Sync CodeQL workflow to additional repos

.sync/Files.yml
The workflow currently builds on Visual Studio due to a CodeQL
extractor bug. ARM packages only build on GCC in CI right now.
=> .sync/Files.yml: Remove CodeQL workflow from mu_silicon_arm_tiano

.sync/Files.yml
Move out of the `repos` list and append onto the preceding group
description.
=> .sync/Files.yml: Move CodeQL workflow comment

.sync/Version.njk, .sync/devcontainer/devcontainer.json
Updates the Linux build container from Fedora 35 to Fedora 37 image.
Closes #145
[14d2aba image](https://github.com/tianocore/containers/pkgs/container/containers%2Ffedora-37-build/75760493?tag=14d2aba)
- [Fedora 35 image contents](https://github.com/tianocore/containers/blob/main/Fedora-35/Readme.md)
- [Fedora 37 image contents](https://github.com/tianocore/containers/blob/main/Fedora-37/Readme.md)
Summary of updates:
- Fedora 35 to Fedora 37 (minimal image)
- NEW: gcc for LoongArch (2022-09-06)
- UPDATED: gcc 11.2.1 to gcc 12.2 (x86, x64, arm, aarch64, riscv)
- UPDATED: Python 3.10 to Python 3.11
- UPDATED: Qemu 6.10 to Qemu 7.2 (x86, arm, aarch64)
- NO CHANGE: nasm 2.15.05
=> .sync/Version.njk: Update Linux build container to Fedora 37 image

.sync/Version.njk, .sync/azure_pipelines/custom/mu_feature_config/Ubuntu-GCC5.yml, .sync/azure_pipelines/custom/mu_feature_ipmi/Ubuntu-GCC5.yml, .sync/azure_pipelines/custom/mu_feature_mm_supv/Ubuntu-GCC5.yml, .sync/azure_pipelines/custom/mu_oem_sample/Ubuntu-GCC5.yml, .sync/azure_pipelines/custom/mu_tiano_platforms/Ubuntu-GCC5.yml, .sync/azure_pipelines/matrix_dependent/Ubuntu-GCC5.yml, .sync/azure_pipelines/matrix_dependent/Windows-VS.yml, Jobs/PrGate.yml, Steps/CommonLogCopyAndPublish.yml, Steps/InstallCoverageTools.yml, Steps/PrGate.yml, Steps/PublishCodeCoverage.yml
1. Switch to coverage files per-matrix to not publish coverage
2. Add steps to download and merge/filter all artifacts
3. Integrates steps into job templates.
Issue #84
=> Create code coverage post-processing steps and integrate into PR Jobs

Steps/BuildBaseTools.yml, Steps/BuildPlatform.yml, Steps/PrGate.yml
Some pipeline now block CmdLine@1 tasks with the error message:
##[error]Task 'Command Line' is using legacy execution handler  which is not supported in container execution flow.
Changed all CmdLine@1 tasks to use CmdLine@2.
=> Updated CmdLine@1 tasks touse  CmdLine@2 

Steps/InstallCoverageTools.yml
Chocolatey is no available in all build evnironments. This change removes the use of choco as a wrapper for downloading and installing opencppcoverage.
=> Directly install opencppcoverage without choco

.sync/workflows/leaf/codeql.yml
Adds caching of PIP dependencies. This reduces overall execution time
and decreases likelihood of a network error reaching out pypi to get
the dependencies.
Caching happens automatically based on pip-requirements.txt.
https://github.com/actions/setup-python#caching-packages-dependencies
Every job before:
```
Run pip install -r pip-requirements.txt --upgrade
Collecting edk2-pytool-library==0.14.0
Downloading edk2_pytool_library-0.14.0-py3-none-any.whl (468 kB)
-------------------------------------- 468.7/468.7 kB 2.7 MB/s eta 0:00:00
Collecting edk2-pytool-extensions==0.22.2
Downloading edk2_pytool_extensions-0.22.2-py3-none-any.whl (2.5 MB)
---------------------------------------- 2.5/2.5 MB 10.7 MB/s eta 0:00:00
Collecting edk2-basetools==0.1.29
Downloading …
```
=> .sync/workflows/codeql.yml: Add PIP module caching

Jobs/PrGate.yml
Allows the caller to specify options passed to the Linux container.
See the following article for more information about `options:`. https://learn.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops#options
=> Jobs/PrGate.yml: Add Linux container option parameter

.sync/workflows/leaf/codeql.yml
PIP modules are not pulled down during the initial job in the CodeQL
workflow (package gathering) so PIP caching is not needed.
Also works around a setup-python task issue that fails to ignore cache
contents if they do not previously exist and are not populated during the job.
=> codeql.yml: Remove PIP caching from pkg gathering

.sync/Files.yml
Syncs the following files to mu_basecore to enable the release
drafter workflow in that repo.
- `release-draft.yml` - Leaf workflow
- `release-draft-config.yml` - Action config file
=> .sync/Files.yml: Sync release drafter to mu_basecore

.sync/dependabot/actions-pip-submodules.yml, .sync/dependabot/actions-pip.yml
Sets the rebase-strategy to "disabled" to prevent automatic rebasing.
This prevents CI resources from building changes that may not actually
be merged for a while (and need to be rebuilt later again).
Rebasing can be done manually in the dependabot PR either through
the GitHub UI or the dependabot command or via a push to the
dependabot PR branch.
=> .sync/dependabot: Disable automatic rebasing

.github/actions/submodule-release-updater/ReadMe.md, .github/actions/submodule-release-updater/action.yml, .sync/Files.yml, .sync/Version.njk, .sync/workflows/leaf/submodule-release-update.yml, ReadMe.rst
Adds an action with a leaf workflow to update submodules in a repository to the latest GitHub release available for the submodule.
Changes:
Adds an action that checks if any submodules in a repository have a
GitHub release available. If so, the submodule is updated to the
latest release and a pull request is made in the repository for
the submodule update.
Syncs a new workflow to update submodules to the latest GitHub
release to mu_tiano_platforms.
Updates to v2.4.0 so the GitHub action is available.
https://github.com/microsoft/mu_devops/compare/v2.3.0...v2.4.0
---
- [Example Action Run on Fork](https://github.com/makubacki/mu_tiano_platforms/actions/runs/4757957469)
Example Pull Requests …
=> Add Submodule Release Updater GitHub Action and Workflow [Rebase & FF]

.sync/dependabot/actions-pip-submodules.yml
Submodules with versioned releases will now be updated with the
Submodule Release Updater action so there is no need for
dependabot to create duplicate PRs for non-release updates of
these submodules.
=> .sync/dependabot: Ignore submodules with versioned releases

.sync/workflows/leaf/submodule-release-update.yml
Surrounds the GitHub token syntax with raw tags to indicate that
the curly braces should not be interpreted as a Nunjucks expression
or variable and treated as a literal.
=> .sync/submodule-release-update.yml: Add Nunjucks raw text tags

.sync/Version.njk
Updates the Fedora 37 build container from f1c7a20 to 3b3eb8f.
- [Fedora 37 image contents](https://github.com/tianocore/containers/blob/main/Fedora-37/Readme.md)
- [3b3eb8f](https://github.com/tianocore/containers/pkgs/container/containers%2Ffedora-37-build/81369123?tag=3b3eb8f)
Summary of updates:
- Enable GTK on Fedora QEMU
- Install vim and nano
- Set up a user to match the outside user
- Add the user to the sudo/wheel group to allow them to use sudo, and set a password
=> .sync/Version.njk: Update Linux build container to Fedora 37 3b3eb8f

.sync/devcontainer/devcontainer.json
Currently the git command fails because the * is not parsed correctly in command line without the quote. This resolves this issue.
=> Add quotes to git safe.directory in .devcontainer to fix parsing error

.sync/workflows/leaf/codeql.yml
Currently, log artifacts are only uploaded in case of success. This
change also uploads logs in case of failures to aid in debugging.
=> .sync/codeql: Attempt to upload logs in case of success and failures

.github/workflows/IssueAssignment.yml, .sync/Files.yml, .sync/workflows/leaf/issue-assignment.yml, ReadMe.rst
Resolves #166
Adds a new GitHub workflow that runs when an issue is assigned.
While additional behavior can be added in the future, right now the
workflow only removes the `state:needs-owner` label if present.
=> Add Issue Assignment workflow

Steps/BinaryCopyAndPublish.yml, Steps/OtherCopyAndPublish.yml
Uses bash to parse a parameter string that could be empty since it
is more robust and consistent than directly depending on pipeline
string interpretation logic.
This treats the following strings as "empty":
- ""
- " "
=> <Binary/Other>CopyAndPublish.yml: Use bash to parse parameter string

.sync/workflows/leaf/codeql.yml
This workflow needs to run against code on the PR merge branch and
since it is just building it only needs minimal, read-only token
permissions so this change updates the trigger type from
`pull_request_target` to `pull_request`.
=> .sync/codeql: Use pull_request trigger type

.sync/dependabot/actions-pip-submodules.yml
The following repos recently moved to semantic versioning so they
can be updated by their versioned releases now instead of dependabot
checking for the latest commit hash.
- [mu_feature_config](https://github.com/microsoft/mu_feature_config/issues/168)
- [mu_feature_mm_supv](https://github.com/microsoft/mu_feature_mm_supv/issues/110)
=> .sync/dependabot: Ignore additional submodules with versioned releases

.github/Labels.yml, .sync/dependabot/actions-pip-submodules.yml, .sync/dependabot/actions-pip.yml, .sync/workflows/config/release-draft/release-draft-config.yml
The `release-drafter` GitHub action has an `exclude-contributors`
configuration option that excludes usernames from the final
contributors. This does not appear to work for dependabot.
The `exclude-labels` configuration option does work. This change
adds a new label `type:dependabot` to dependabot PRs (via the
dependabot config file) and uses the `exclude-labels` option in
the `release-drafter` config file to exclude those PRs from release
notes.
Submodules are currently updated by either `dependabot` or the
`submodule-release-updater` GitHub action local to mu_devops. Since
submodules are recursive to repo consumers and to keep those
consistently in the release notes, the `type:dependabot` label is
not added to dependabot submodule updates keeping those updates in
the release notes.
=> Add a dependabot label and exclude it from release notes 

.sync/Files.yml, .sync/Version.njk
Updates the `latest_mu_release_branch` value substituted into sync
templates from `release/202208` to `release/202302`.
=> .sync/Version.njk: Update latest Mu release branch to 202302

.sync/Files.yml
More repos with `release` branches are moving to versioned releases
so the release drafter workflow is synced to them in this change.
New repos:
- microsoft/mu_common_intel_min_platform
- microsoft/mu_oem_sample
- microsoft/mu_plus
- microsoft/mu_silicon_arm_tiano
- microsoft/mu_silicon_intel_tiano
- microsoft/mu_tiano_plus
=> .sync/Files.yml: Sync release drafter to additional repos

.sync/Version.njk, .sync/azure_pipelines/custom/mu_feature_config/Ubuntu-GCC5.yml, .sync/azure_pipelines/custom/mu_oem_sample/Ubuntu-GCC5.yml, .sync/azure_pipelines/matrix_dependent/Ubuntu-GCC5.yml, .sync/devcontainer/devcontainer.json
Updates the default Linux build container from Fedora 37 to
Ubuntu 22.
The container feed switched from `ghcr.io/tianocore/containers`
to `ghcr.io/microsoft/mu_devops`.
Note: This is marked as a breaking change because of the distro change
from Fedora to Ubuntu. Commands run inside the container such as those
interacting with the package manager need to be reviewed and updated.
=> .sync/Version.njk: Switch to Project Mu Ubuntu 22 containers

.sync/Version.njk
https://github.com/microsoft/mu_devops/compare/v2.5.3...v3.0.0
A major release is being made because of a change in the container
images used in Project Mu pipelines.
=> .sync/Version.njk: Update Mu repos to Mu DevOps v3.0.0

.sync/Files.yml
Additionally syncs the file to mu_devops since it is missing. Also
prevents the `microsoft-github-policy-service` bot from creating PRs
to add a SECURITY.md file.
=> .sync/Files.yml: Sync SECURITY.md to mu_devops

.sync/dependabot/actions-pip-submodules.yml, .sync/dependabot/actions-pip.yml
Checks for PIP module updates weekly instead of daily. The number of
updates was too frequent for CI resources and reviewer overhead.
Also explicitly sets the submodule weekly update day to Tuesday so
PIP and submodules updates can both be available Wednesday morning
for review and merge.
=> .sync/dependabot: Update PIP modules weekly

Notebooks/PullRequests.github-issues
Updates the year from `2022` to `2023` to reduce the total number of
PRs returned (which is limited by GitHub).
=> Notebooks/PullRequests.github-issues: Bump completed PR start date

Jobs/PrGate.yml
Current pipeline job for publishing coverage will skip the jobs if there are a few jobs being skipped. However, some skips are expected, such as some jobs that should be run on selfhosted agents, but no agents are available on the public site.
This change will update the publish coverage job's condition to ignore the skipped conditions, such that it will always run the job as long as there the previous job(s) not failing or being cancelled.
=> Publish coverage on even with skipped builds

Containers/Ubuntu-22/Dockerfile
This removes the need for pipeline files to add this path, and simplified use of the container.
=> Add the azure container user local bin to container path

.github/workflows/Labeler.yml
Updates `github/issue-labeler` from `v2.5` to `v3.1`.
Includes the following fixes (occassionally impacting Mu PRs):
- Issue labels that do not match a regex will no longer be removed
- Support empty body and only remove existing labels
---
Updates `actions/labeler` from `v4` to `v4.1.0`.
No major known changes that impact Mu DevOps.
=> .github/workflows/Labeler.yml: Update workflows

.sync/Version.njk
https://github.com/microsoft/mu_devops/compare/v4.0.0...v4.0.5
In particular, this rolls out an update to the issue labeler action
to bring it up to latest.
=> .sync/Version.njk: Update Mu repos to Mu DevOps v4.0.5

.github/workflows/ReleaseDrafter.yml, .sync/Version.njk
The `*_mu_branch` workflow variables were not set in some cases to
reduce workflow execution time but logically the variables should
be set to ensure the step conditionals work as expected.
=> ReleaseDrafter.yml: Set Mu branches in all cases [Rebase & FF]

.sync/Version.njk
https://github.com/microsoft/mu_devops/compare/v5.0.1...v5.0.4
- The `ubuntu-22-build` container image is also updated to the latest: `ea6d2e6`.
=> .sync/Version.njk: Update Mu repos to Mu DevOps v5.0.4

Jobs/CreateBuildMatrix.yml, Steps/BuildPlatform.yml, Steps/PrGate.yml, Steps/RunPatchCheck.yml
https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines#shallow-fetch
`New pipelines created after the [September 2022 Azure DevOps sprint 209 update](https://learn.microsoft.com/en-us/azure/devops/release-notes/2022/sprint-209-update) have Shallow fetch enabled by default and configured with a depth of 1. Previously the default was not to shallow fetch. To check your pipeline, view the Shallow fetch setting in the [pipeline settings UI](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git#shallow-fetch).`
Adding fetchdepth of 0 to disable default of shallow checkout for new pipelines using mu_devops.
=> Added fetchdepth to disable default shallow checkout in new pipelines

Steps/PublishCodeCoverage.yml
A specific container that does checkout prior to running mu_devops runs into problems with multiple checkout statements. It places the repo under multiple directories.
Adding a parameter to prevent checkout of the repo again for the code coverage step.
=> Add checkout_self parameter to prevent additional checkouts

.sync/Version.njk
https://github.com/microsoft/mu_devops/compare/v5.0.4...v5.0.6
- The `ubuntu-22-build` container image is also updated to the latest: `3bf70b5`.
=> .sync/Version.njk: Update Mu repos to Mu DevOps v5.0.6 (and container)

Containers/Ubuntu-22/Dockerfile
Resolves #228 
Recently acpica.org has been unavailable, see:
https://github.com/acpica/acpica/issues/888
Project Mu already publishes iasl to a NuGet feed. To fix the
immediate container build issue and reduce external dependencies for
the future, this change gets iasl from the NuGet feed instead of from
acpica.org. A NuGet client application is not involved to keep the
container build steps light.
The executable is moved to `/usr/bin` which is already on the system
path.
=> Containers/Ubuntu-22/Dockerfile: Get iasl from Project Mu NuGet feed

.sync/Version.njk
Adds the Rust toolchain version to the file so it can be referenced
in future changes that add Rust support to the repo.
This change needs to be broken out because the upcoming change will
refer to this entry in Version.njk in the main branch when testing
the container build in its PR checks.
=> Version.njk: Add Rust toolchain version

.azurepipelines/GetCargoMake.yml, .azurepipelines/GetCargoTarpaulin.yml, .sync/Files.yml, .sync/azure_pipelines/MuDevOpsWrapper.yml, .sync/azure_pipelines/RustSetupSteps.yml, .sync/rust_config/Makefile.toml, .sync/rust_config/rust-toolchain.toml, .sync/rust_config/rustfmt.toml, Containers/Ubuntu-22/Dockerfile, Jobs/PrGate.yml, Scripts/DownloadCargoBinaryFromGitHub/DownloadCargoBinaryFromGitHub.py, Scripts/DownloadCargoBinaryFromGitHub/Readme.md, Steps/PrGate.yml, Steps/RustCargoSteps.yml, Steps/RustSetupSteps.yml
This pull request adds Rust support to mu_devops with patterns that extend to Rust adoption in additional Project Mu repos.
The changes can be grouped into three high-level parts:
1. Sync Rust environment files to repos
2. Add pipeline support to build and test Rust code 
3. Update the build container to incorporate Rust support
These changes extend existing Rust efforts in Project Mu and improve user experience outside the CI environment.
---
---
These files are added so dedicated pipelines can download the latest
release from each tools GitHub repository and push the binaries to
the pipeline artifacts.
Project Mu pipelines dependent on Rust tools can access the tools
directly from the Project Mu pipeline artifacts which is faster
than building and more reliable than depending on …
=> Add Rust Support [Rebase & FF]

.sync/Version.njk
https://github.com/microsoft/mu_devops/compare/v5.0.6...v6.0.0
- The `ubuntu-22-build` container image is also updated to the latest: `9ab29bc`.
- Note: This is the first release with Rust dev support.
- v6.0.0 also brings some new changes in the pipelines for Project Mu repos to build rust in CI.
=> .sync/Version.njk: Update Mu repos to Mu DevOps v6.0.0 (and container)

.sync/devcontainer/devcontainer.json
`core.autocrlf = true` is a common pitfall when edk2 developers create a new file. It is always suggested to have this git config value turned off when developing EDKII UEFI firmware. Updates the container to have this git config set as expected.
=> set autocrlf to false in containers

.sync/workflows/leaf/codeql.yml
Updates the workflow to be able to build Rust code if present in
a repo. The Rust toolchain is installed by default, so this simply
installs `cargo make` and installs `rust-src`.
`cargo-make` is cached so it can be reused across runs until the
next version is published in the upstream repo.
=> .sync/codeql: Add cargo make and install rust-src

.sync/azure_pipelines/RustSetupSteps.yml
Updates the workflow to be able to build Rust code if present in
a repo. The Rust toolchain is installed by default, so this simply
installs `cargo make` and installs `rust-src`.
`cargo-make` is cached so it can be reused across runs until the
next version is published in the upstream repo.
=> .sync/RustSetupSteps.yml: Update leaf file to match current

.sync/Files.yml, .sync/azure_pipelines/MuDevOpsWrapper.yml
Two changes:
**Add `extra_cargo_steps` parameter in MuDevOpsWrapper.yml**
The `extra_cargo_steps` parameter allows a repo extending
MuDevOpsWrapper.yml to specify a step list that should be executed
before running the standard set of cargo commands in the repo
(to build and test).
---
**Opt mu_tiano_platforms into Rust file sync**
Syncs the normal set of workspace-level Rust files to the
mu_tiano_platforms repo.
=> Add mu_tiano_platforms to Rust Sync

.sync/Files.yml, .sync/workflows/leaf/codeql-platform.yml
Adds a new GitHub workflow that allows CodeQL to run against platform
builds. Previously, only a "CI" CodeQL workflow existed
(`.sync\workflows\leaf\codeql.yml`) that did not support platform
builders.
The CodeQL platform workflow is agnostic to specific platform details.
It works by discovering all buildable platforms in a repo before any
dependencies are cloned and then verifying the build files in the
platform package directory support platform build. If they do, it is
checked if they support CodeQL. Only platforms that meet all of these
conditions are actually built via a dynamic platform package matrix.
This allows the workflow to scale across platform repos and
automatically pick up new platforms as they onboard support for
CodeQL.
---
Tested in `mu_tiano_platforms`.
=> Add CodeQL platform GitHub workflow

.sync/rust_config/Makefile.toml
The VS Code `rust-analyzer` plugin uses `cargo check` to find
problems. We use custom flags/target info with `cargo make`.
This adds a `cargo make check` command that reuses similar
flags to our build so the check results are similar. `check_json`
is added to be used by tools like VS Code that need JSON
output.
=> .sync/rust_config/Makefile.toml: Add check task

.sync/workflows/leaf/codeql-platform.yml, .sync/workflows/leaf/codeql.yml
Intermediate build files are sometimes left in build directories
during CodeQL execution. This is particularly more prevalent in
module directories that contain Rust files. These files have very
long names, for example:
```
D:\a\mu_tiano_platforms\Build\QemuQ35Pkg
\DEBUG_VS2022\X64\MsCorePkg\HelloWorldRustDxe\HelloWorldRustDxe
\DEBUG\x86_64-unknown-uefi\debug\incremental
\rust_boot_services_allocator_dxe-2f5m6unckl0t8
\s-gorl2pbwn9-18oh534-e4zntah436u40i7hceav0825j
```
CodeQL actions have well known and unresolved issues with long paths
when they're scanning directories for files.
The directories where these files may be left are not needed after
build and it takes about 3 seconds to remove them so that is done
in this change.
---
Tested on fork. Example: …
=> .sync/workflows/leaf/codeql: Remove build dirs

.sync/azure_pipelines/RustSetupSteps.yml, Steps/RustSetupSteps.yml
Adds a step to determine the target triple for the host platform
that can be reused by other steps. It is currently used in the
`rustup component add` command issued later in the file.
=> RustSetupSteps: Add target triple detection

.sync/rust_config/Makefile.toml
Tarpaulin 0.27 was released on September 17, 2023:
https://github.com/xd009642/tarpaulin/releases/tag/0.27.0
The clap crate (Command Line Argument Parser) dependency within
tarpaulin was upgraded in the 0.27 release from an old version
(v2) to the latest major version (v4):
```
Upgraded from clap v2 to v4. This has a few changes, notably any
arguments which can be specified more than once require multiple
entries so --run-types doc test needs to be turned into
--run-types doc --run-types test
```
This means passing packages to a single `-p` parameter as a comma-
separated list is no longer supported:
```
[cargo-make] Execute Command: "cargo" "tarpaulin" "-p" \
"HelloWorldRustDxe,RustBootServicesAllocatorDxe"
cargo_tarpaulin::config: Creating config
cargo_tarpaulin: Running Tarpaulin …
```
=> .sync/Makefile.toml: Resolve cargo-tarpaulin breaking changes

.sync/Files.yml
Do not sync the file since the repo is not planned to host UEFI rust
code at this time which the makefile helps cater to.
=> .sync/Files.yml: Drop Makefile.toml sync to mu_rust_hid

.sync/azure_pipelines/MuDevOpsWrapper.yml, Steps/RustCargoSteps.yml
Allows the format, test, and build commands to be customized by a
caller. The default values remain the same as the previous commands
for backward compatibility.
Repos that only contain pure Rust code may choose to pass conventional
cargo commands or custom wrapper commands.
=> Steps/RustCargoSteps.yml: Parameterize commands

.github/actions/submodule-release-updater/action.yml, .sync/Version.njk, .sync/workflows/leaf/codeql-platform.yml, .sync/workflows/leaf/codeql.yml, Steps/SetupPythonPreReqs.yml
Because of the way the Python version was managed, pipelines already
started picking up [Python 3.12](https://www.python.org/downloads/release/python-3120/).
Also, tool like pytools are releasing 3.12 support. This change fixes
the minor version to prevent unintentional minor version updates in
the future and explicitly sets the minor version to `12`.
This files synced from this PR should merged into repos after the pytools
release is out with 3.12 support and this mu_basecore change is completed
(https://github.com/microsoft/mu_basecore/pull/586). Though since pipelines
already moved to 3.12 as-is, it won't make much of a practical difference.
Three commits:
---
**Fix Python minor version**
Set to Python 3.11 (current) but do not allow newer minor versions to
be picked up unless …
=> Fix Python minor version and update to Python 3.12 [Rebase & FF]

.sync/Version.njk
https://github.com/microsoft/mu_devops/compare/v7.0.0...v7.0.1
Also updates the container to the latest version `1082f35`.
=> .sync/Version.njk: Update Mu repos to Mu DevOps v7.0.1

.sync/workflows/leaf/codeql-platform.yml, .sync/workflows/leaf/codeql.yml
Excludes tools that are not necessary to be present for CodeQL builds.
---
Can precede but pairs with [BaseTools/Plugin: Add tool exclusion to RustEnvironmentCheck](https://github.com/microsoft/mu_basecore/pull/602)
=> .sync/workflows: Pass Rust env tool exclusions in CodeQL flows

.sync/azure_pipelines/MuDevOpsWrapper.yml, Jobs/PrGate.yml, Steps/PrGate.yml, Steps/PublishCodeCoverage.yml
Update code coverage calculations to have the ability to reorganize the report by INF using `stuart_parse` and `stuart_report.`
I have confirmed this as working using MuDevOpsWrapper for MU_BASECORE PRs:
Windows: [Pipelines - Run 20231102.11 (azure.com)](https://dev.azure.com/projectmu/mu/_build/results?buildId=57362&view=codecoverage-tab)
Linux: [Pipelines - Run 20231102.11 (azure.com)](https://dev.azure.com/projectmu/mu/_build/results?buildId=57363&view=codecoverage-tab)
=> Update Code Coverage Calculations

.sync/Version.njk
https://github.com/microsoft/mu_devops/compare/v7.0.1...v7.1.0
---
This change is necessary when integrating 649a4ba to prevent the following failure:
```
/.azurepipelines/MuDevOpsWrapper.yml (Line: 92, Col: 30): Unexpected
parameter 'calculate_code_coverage'
```
=> .sync/Version.njk: Update Mu repos to Mu DevOps v7.1.0

Steps/UploadCodeCoverage.yml
Contains two changes related to uploading code coverage:
1. Remove edk2toollib dependency
Some repos (like pure Rust repos) are expected not to depend on
pytools. Since the codecov application can simply be run without
`RunCmd()`, do that and prevent the need for those repos to depend
on edk2toollib or unnecessary logic in the pipelines to bring it in.
2. Conditionalize coverage upload steps on codecov token presence
Some repos may not upload to codecov for various reasons. Those repos
won't set the code coverage token so conditionalize the upload steps
on the token.
---
Will unblock https://github.com/microsoft/mu_rust_hid/pull/12
=> Steps/UploadCodeCoverage.yml: Remove dependency and conditionalize [Rebase & FF]

.sync/Version.njk, .sync/azure_pipelines/MuDevOpsWrapper.yml, Jobs/PrGate.yml, ReadMe.rst, Steps/PrGate.yml, Steps/UploadCodeCoverage.yml
This PR contains multiple updates to code coverage when executed via MuDevOpsWrapper.yml
1. Removed calculate_code_coverage - This was redundant, as `coverage_publish_target` could be used instead (by having it not set, or selecting codecov / ado
2. Updates all usage of `coverage_publish_target` to be condition of a step, rather than used in a compile time expression for adding / removing steps. This is to support setting the parameter via pipeline variables. This has the unfortunate side effect of the steps always being present in the pipeline build, just skipped, which is not as clean as before.
3. Updates ado code coverage uploads to be per-matrix-job by utilizing `PublishCodeCoverageResults@2` which can merge code coverage results. This resolves #267
4. Resolves #276 by passing the …
=> Multiple Updates to code coverage

.sync/azure_pipelines/MuDevOpsWrapper.yml, Jobs/PrGate.yml, ReadMe.rst, Steps/PrGate.yml, Steps/UploadCodeCoverage.yml
the `values` config does not work as variables are not evaluated until the step runs, so what actually gets passed and verified against the `values` config ends up being the string `$(variable_name)`, which always fails as we were saying the value could only be "ado" or "codecov" or ""
This PR updates all yaml files to no longer pass the environment variable as a parameter from `MuDevOpsWrapper` -> `Jobs/PrGate` -> `Steps/PrGate` -> `UploadCodeCoverage` and instead uses the environment variable directly in `UploadCodeCoverage` All aforementioned yaml files have been updated with documentation on how to generate code coverage.
=> MuDevOpsWrapper.yml: Bugfix bad value options

.sync/Files.yml
Adding a first pass of filesync for the secureboot_objects repo. 
@makubacki @Flickdm 
Please verify that all necessary files are being sycned in this PR.
=> Start file sync for secureboot_objects repo

.github/actions/submodule-release-updater/action.yml, .sync/workflows/leaf/codeql-platform.yml, .sync/workflows/leaf/codeql.yml
Updates the sync files to use v5 so they will match the latest files
updated by dependabot in the synced repo. Also updates the version in
the file in the submodule-release-updater action.
=> Bump setup-python action from v4 to v5 in sync files

.sync/workflows/leaf/codeql-platform.yml, .sync/workflows/leaf/codeql.yml
Two key new restrictions:
1. No more than 10 artifacts per job in a workflow run.
2. It is no longer possible to upload to the same named artifact
multiple times.
These workflows can easily split their artifacts up under the 10
artifact limit while also not uploading to the same named artifact
in the process.
---
Tested:
- `codeql.yml` - [Mu Basecore Action Run 7258088601](https://github.com/makubacki/mu_basecore/actions/runs/7258088601)
- `codeql-platform.yml` - [Mu Tiano Platforms Action Run 7257959608](https://github.com/makubacki/mu_tiano_platforms/actions/runs/7257959608)
=> .sync/workflows/leaf: CodeQL workflow changes for upload-artifact v4

.sync/rust_config/Makefile.toml
Adds additional environment variables to the Makefile.toml to set features when building.
setting the variable `FEATURES` will translate to passing `--features <features>` to the underlying build command.
=> Rust: Makefile.toml: Add Feature flag support

.sync/workflows/leaf/codeql-platform.yml, .sync/workflows/leaf/codeql.yml
The CodeQL plugin moved from .pytool to BaseTools in the Mu Basecore 202311 update. This change first looks for the plugin in BaseTools and falls back to the prior .pytool location if it is not found for backward compatibility with some earlier release branches that have not picked up the change.
Eventually, the .pytool fallback can be removed.
---
Issue to track removal of the fallback: https://github.com/microsoft/mu_devops/issues/300
=> .sync/workflows/leaf/codeql.yml: Update CodeQL plugin from .pytool to BaseTools

.sync/workflows/leaf/codeql.yml
With the CodeQL plugin moving to BaseTools (from .pytool) starting in release/202311, update the workflow to always remove unnecessary plugins (that slow down the workflow) in .pytools as opposed to relative the CodeQL plugin path.
=> .sync/workflows/codeql: Always remove plugins in .pytools

.sync/workflows/leaf/codeql.yml
The latest codeql.yml change updated the cleanup step to find .pytool/Plugin folder directly instead of using a relevant path form the CodeQL plugin directory.
That change didn't take into account how all branches from release/202302 and older have the .pytool/Plugin version of CodeQL and was deleting all plugins in .pytool besides CompilerPlugin. This change excludes the CodeQL plugin if it exists as well.
=> Fix issue with .pytool/Plugin removal which was introduced with the latest codeql.yml change.

.sync/workflows/leaf/codeql-platform.yml, .sync/workflows/leaf/codeql.yml
Updates the CodeQL workflows to match the latest version that is
being updated by dependabot in relevant repos.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/robinraju/release-downloader/releases">robinraju/release-downloader's releases</a>.</em></p> <blockquote>
<h2>Release Downloader v1.9</h2>
<h2>What's Changed</h2>
<ul>
<li>Correct minor typo in extract action input by <a href="https://github.com/philostler"><code>@​philostler</code></a> in <a href="https://redirect.github.com/robinraju/release-downloader/pull/666">robinraju/release-downloader#666</a></li> <li>Fix broken link to CI status badge on README by <a href="https://github.com/robinraju"><code>@​robinraju</code></a> in <a href="https://redirect.github.com/robinraju/release-downloader …
=> GitHub Action: Bump robinraju/release-downloader from 1.8 to 1.9

.github/workflows/AutoMerger.yml, .github/workflows/FileSyncer.yml, .github/workflows/IssueAssignment.yml, .github/workflows/IssueTriager.yml, .github/workflows/LabelSyncer.yml, .github/workflows/Labeler.yml, .github/workflows/ReleaseDrafter.yml, .sync/Version.njk, .sync/workflows/leaf/auto-approve.yml, .sync/workflows/leaf/auto-merge.yml, .sync/workflows/leaf/issue-assignment.yml, .sync/workflows/leaf/label-issues.yml, .sync/workflows/leaf/label-sync.yml, .sync/workflows/leaf/pull-request-formatting-validator.yml, .sync/workflows/leaf/release-draft.yml, .sync/workflows/leaf/scheduled-maintenance.yml, .sync/workflows/leaf/stale.yml, .sync/workflows/leaf/submodule-release-update.yml, .sync/workflows/leaf/triage-issues.yml
Add permissions to the workflows across mu_devops. This includes the workflows sync'd across repositories, and workflows used in mu_devops itself. 
With MU_BASECORE's Settings -> Code and automation -> Actions -> General -> Workflow permissions set to "Read repository contents and packages permissions" selected, I had no failures, with the following tested:
.github/workflows
- **AutoMerger.yml - Untested**
- FileSyncer.yml - Tested
- IssueAssignment.yml - Tested
- IssueTriager.yml - Tested
- LabelSyncer.yml - Tested
- Labeler.yml - Tested
- ReleaseDrafter.yml - Tested
.sync/workflows/leaf
- **auto-approve.yml - Untested**
- **auto-merge.yml - Untested**
- issue-assignment.yml - Tested through IssueAssignment.yml
- label-issues.yml - Tested through Labeler.yml
- label-sync.yml - Tested …
=> workflows: Add permissions.

.github/workflows/ReleaseDrafter.yml, .sync/Files.yml, .sync/Version.njk, Scripts/TagGenerator/Readme.md
Updates the latest and previous branches to 202311 and 202308.
Also updates references to 202302 throughout the repo to prevent the
examples from getting too stale over time.
=> .sync/version.njk: Update latest Mu branch to 202311

.sync/Version.njk
Updates the mu_devops version in Version.njk to 9.1.2 in preparation for a 9.1.2 release of mu_devops that will be sync'd.
=> Update Version.njk for release

.sync/Version.njk
Update the Ubuntu build container to an image that includes Rust 1.74.
=> .sync/Version.njk: Update Ubuntu container image

Jobs/PrGate.yml, Steps/PrGate.yml
extra_install_step is moved to after stuart_update.
extra_install_steps can be used to pass a call to another stuart_update to include the --codeql parameter.
=> Introduce extra_build_args to Jobs/PrGate.yml. Move extra_install_steps to after stuart_update call. 

.sync/workflows/leaf/codeql-platform.yml, .sync/workflows/leaf/codeql.yml
Two commits. One to prepare `codeql-platform.yml` for 202311 and the other
to expand contextual comments in both CodeQL workflow files.
---
**.sync/workflows/codeql-platform: Update irrelevant plugin removal dir**
Updates the directory used for irrelevant plugin removal in this
workflow to match codeql.yml which using the pytool directory rather
than the directory the CodeQL plugin is found in.
This is important because the CodeQL plugin moved from .pytool to
BaseTools in Mu release 202311 so the plugin dir needs to be fixed
rather than relative to the CodeQL plugin location.
---
**.sync/workflows/codeql: Add more inline documentation**
Updates and adds some additional comments to the CodeQL workflow
files to give better context.
=> .sync/workflows/codeql-platform: Update irrelevant plugin removal dir [Rebase & FF]

.azurepipelines/GetCargoBinstall.yml, Scripts/DownloadCargoBinaryFromGitHub/DownloadCargoBinaryFromGitHub.py
Adds a pipeline to cache cargo binstall.
Adds `.tgz` (short for `.tar.gz`) support to the DownloadCargoBinaryFromGitHub.py script. Also fixes a logic error in the conditional that decides which assets to download.
See successful pipeline run: https://dev.azure.com/projectmu/mu/_build/results?buildId=64211&view=logs&j=402df595-8a03-57d0-41e1-0654a1932349
=> Add pipeline to cache cargo binstall

Steps/NuGet.yml
Need to switch mu_devops to use NuGetAuthenticate@1 tasks. NuGetAuthenticate@0 is being depreciated, in some pipelines, starting 2024.01.31.
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/nuget-authenticate-v0?view=azure-pipelines
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/nuget-authenticate-v1?view=azure-pipelines
Fixes #289
=> Change NuGetAuthenticate task to version 1.

.sync/Version.njk, .sync/azure_pipelines/RustSetupSteps.yml, .sync/rust_config/rust-toolchain.toml
Update RustSetupSteps to download cargo-binstall and use it to download all other rust tools. This is to make it easy for CI to pass the updated RustEnvironmentCheck (https://github.com/microsoft/mu_basecore/pull/737) by downloading the exact tool versions as specified in the rust-toolchain.toml file.
=> Use cargo-binstall to sync rust tool versions

.sync/Files.yml, .sync/workflows/leaf/codeql-platform.yml, .sync/workflows/leaf/codeql.yml
Most of the workflow can stay intact with GitHub caching working
as-is but the cargo-make version now needs to match the version that
is being synced to repos (i.e. matches rust-toolchain.toml).
---
Note: We can consider using cargo binstall in the future but right now
only cargo-make is needed, and it is simple to directly cache that binary
as-is with existing code.
=> .sync/workflows/codeql: Use Version.njk cargo-make version

.sync/workflows/leaf/codeql-platform.yml
Removes the -t and -a command flags for the codeql-platform.yml workflow when executing stuart_build. Neither of these command line arguments are provided by the edk2_platform_build invocable. the target is set via TARGET=<value> for platforms, and the architecture is not set at all, as platforms hardcode the required architectures.
Sets the target via the expected way, TARGET=DEBUG.
=> codeql-platform.yml

.sync/Version.njk, .sync/azure_pipelines/RustSetupSteps.yml, Steps/RustSetupSteps.yml
By default `rusup` performs a self-update when installing a new rustc toolchain, Sometimes, the files are locked by windows, and the self update can fail as described here: https://github.com/rust-lang/rustup/issues/2441
Since this is a pipeline run, we have no need to update rustup, and can rely on the version provided by the runner. By disabling the self update, the file conflict `The process cannot access the file because it is being used by another process` no longer appears as seen in this test PR: https://dev.azure.com/projectmu/mu/_build/results?buildId=65795&view=results
=> Prevent rustup self update

.sync/Version.njk
https://github.com/microsoft/mu_devops/compare/v9.1.8...v9.1.9
---
This change is needed to finishing syncing the Rust version update change.
=> .sync/Version.njk: Update Mu repos to Mu DevOps v9.1.9

.sync/Version.njk
Only change is building with Rust 1.76.0 instead of Rust 1.74.0.
=> Version.njk: Update Ubuntu 22 container for Rust 1.76.0

.sync/workflows/leaf/codeql-platform.yml, .sync/workflows/leaf/codeql.yml
Matches latest version synced to repos with dependabot.
=> .sync/workflows/codeql: Bump release-downloader from v1.9 to v1.10

Steps/BuildPlatform.yml, Steps/PrGate.yml
SetupPythonPreReqs.yml already has a parameter with default set to true, but the user cannot change it. So, extending the install_pip_modules paramter, so that the user can override it
=> Steps/BuildPlatform.yml & Steps/PrGate.yml: Add parameter to install pip modules

.sync/Version.njk, Steps/BuildPlatform.yml, Steps/PrGate.yml
`-a` is not a first class parameter for stuart_build, so mu_devops should not expect that it exists. If a platform has added a necessary `-a` argument, then they can pass it to the command in mu_devops through the `build_flags` for BuildPlatform.yml or ` extra_build_args` for PrGate.yml
=> remove `-a` flag on stuart_build commands

.sync/Files.yml, Notebooks/MyPullRequests.github-issues, Notebooks/OpenIssues.github-issues, Notebooks/PullRequests.github-issues
Mu Rust Pi (https://github.com/microsoft/mu_rust_pi) hosts Rust code
for the Platform Initialization (PI) Specification.
This change sets up file syncing to the repo and adds the repo to the
GitHub notebooks.
=> Onboard Mu Rust PI to Mu DevOps

.sync/workflows/leaf/codeql-platform.yml
The `-a` parameter was recently removed from platform pipeline files.
This change follows the pattern of depending on platforms to specify
their default architecture for the build.
=> codeql-platform.yml: Remove arch

.sync/workflows/leaf/codeql-platform.yml, .sync/workflows/leaf/codeql.yml
Attempts sometimes fail on the first try and later succeed when
reaching out to the GitHub REST API. To prevent actions from having
to be rerun, try up to 5 times waiting 10 seconds between each try.
=> .sync/codeql: Add retry on GitHub REST Access Failures

.sync/workflows/leaf/codeql-platform.yml, .sync/workflows/leaf/codeql.yml
Matches latest version synced to repos with dependabot.
=> .sync/workflows/codeql: Bump release-downloader from v1.10 to v1.11

.sync/Files.yml, .sync/rust_config/config.toml
Currently sets the ImageBase in the PE/COFF header to
`0` as expected for UEFI images.
The cargo config file will be synced to Rust enabled
repos to apply the linker flags regardless of whether
the Rust code is compiled directly or through the
firmware build system.
=> Set ImageBase to 0 and Subsystem to EFI Boot Services in config.toml

.sync/github_templates/contributing/CONTRIBUTING.md, .sync/github_templates/pull_requests/pull_request_template.md
- Remove a lot of boilerplate text
- Point to checkbox instructions instead of inplace instructions
- Points to a single consistent location on the "mu" repo
- Update the `CONTRIBUTING.md` file in each repo to elaborate on how to fill out the PR template
---
There is a follow up item tracked in https://github.com/microsoft/mu_devops/issues/358 to make PR descriptions more consistently filled out so they appear as expected in release notes.
=> .sync: Simply PR description template

.github/workflows/ReleaseDrafter.yml, .sync/Files.yml, .sync/Version.njk, Scripts/TagGenerator/Readme.md
Also updates references to 202302 throughout the repo to prevent the examples from getting too stale over time.
=> .sync/version.njk: Update latest Mu branch to 202405

.sync/Version.njk
Update to a newer Rust toolchain in order to incorporate improvements with newer versions.
For example, an improvement on the size optimization of output rust binaries.
=> Update the Rust toolchain to version 1.80.0

.sync/Version.njk, Steps/RustSetupSteps.yml
Update to the latest version of cargo_tarpaulin, release 31.2. This change is required to allow tarpaulin to function with Rust toolchain 1.80. Running tarpaulin 27.3 with toolchain 1.80 results in the tool failing with a "Parse error".
=> RustSetupSteps.yml: Update to latest cargo_tarpaulin 31.2 and Rust Toolchain

Steps/BuildPlatform.yml
Adds a True / False parameter to the BuildPlatform step to allow disabling PR evaluation, similar to that of Steps/PrGate.yml. Default value is True to match current behavior.
=> Steps/BuildPlatform: Add toggle for stuart_pr_eval

.sync/dependabot/actions-pip-submodules.yml
Let the submodule-release-updater GitHub action handle updates based on versioned GitHub releases.
=> .sync/dependabot: Add Features/DEBUGGER to ignore list

.sync/Version.njk
Main reason to update is to use the latest Rust versions
in Version.njk.
```
{# The Rust toolchain version to use. #}
{% set rust_toolchain = "1.80.0" %}
{# Rust tool versions. #}
{% set cargo_make = "0.37.9" %}
{% set cargo_tarpaulin = "0.31.2" %}
```
A complete list of changes compared to the previous container
version (`0e124c1`) is in:
https://github.com/microsoft/mu_devops/compare/0e124c1...d1e4ff1
=> Version.njk: Update to container version d1e4ff1

Jobs/PrGate.yml, Steps/PrGate.yml
Adds a new template parameter called `extra_pre_build_steps` that allows a step list to run before any stuart build related commands are executed.
=> PrGate.yml: Add extra_pre_build_steps param

Containers/Ubuntu-22/Dockerfile
QEMU Version 9.0.0 is required for SMMU and GIC support on the sbsa-ref machine. This version is already used in the mu_tiano_platforms ext-dep
=> Containers: Update QEMU to version 9.0.0

.sync/Files.yml, .sync/Version.njk, .sync/actions/submodule-release-updater-action.yml, .sync/azure_pipelines/SetupPythonPreReqs.yml, .sync/containers/Ubuntu-22/Dockerfile, .sync/workflows/leaf/codeql-platform.yml, .sync/workflows/leaf/codeql.yml
**Define Python version once**
Defines the Python version in a single location `Version.njk` and
syncs that version to other files. Sets the Python version to 3.12
(although 3.13 was recently released) for continued compatibility
with the version already used in Windows pipelines.
---
**.sync/Version.njk: Update to Mu DevOps v12.2.0**
See the following comparison for details of the changes
between these releases:
https://github.com/microsoft/mu_devops/compare/v12.0.2...v12.2.0
---
Note: Testing is in progress.
=> Use a Single Python Version Definition [Rebase & FF]

.sync/containers/Ubuntu-22/Dockerfile
Some additional steps are needed to move the container build to Python 3.12.
The Deadsnakes PPA is needed to get Python 3.12. Add a step to add that repo and then use apt to install Python 3.12 from it. gnupg is needed to add the key for Deadsnakes. Distutils was removed from Python 3.12 but we still need it to build QEMU so that is added as a separate installation.
---
Changes tested in https://github.com/microsoft/mu_devops/pull/382
=> .sync/Dockerfile: Add Python 3.12 installation steps

.sync/Version.njk
Main reason to update is to pick up the latest Ubuntu container build that uses Python 3.12.
A complete list of changes compared to the previous container version (`d1e4ff1`) is in:
https://github.com/microsoft/mu_devops/compare/d1e4ff1...4bebc96
=> Version.njk: Update to container version 4bebc96

.sync/Files.yml, .sync/github_templates/pull_requests/pull_request_template.md, .sync/workflows/config/label-issues/regex-pull-requests.yml, .sync/workflows/leaf/backport-to-release-branch.yml
Closes #372 
This new workflow will attempt to automatically cherry-pick marked contributions to a development branch to its corresponding release branch. If a merge conflict occurs, the commit is committed to a new branch with merge markers and then a PR is created into the target branch with those markers. The PR is labeled with
`type:release-merge-conflict` to indicate that it needs manual resolution.
The PR (if created) is expected to fail compilation and status checks of course due to the merge conflict markers. A human should then checkout the PR branch, resolve the conflicts, and push the changes back to the PR branch.
---
- To mark a PR going into the development branch so that it should be cherry-picked to the release branch, add the `type:backport` label to the PR.
---
Notes:
- …
=> Add release branch backport workflow

.sync/rust_config/rustfmt.toml
Add arguments to rustfmt for vertically aligning struct and enum members. Usage requires `+nightly`.
Value of 8 matches 'align_var_struct_span' from uncrustify.cfg.
=> .sync/rust_config/rustfmt.toml: Add struct and enum alignment

.github/workflows/ReleaseDrafter.yml, .sync/Files.yml, .sync/workflows/config/release-draft/release-draft-config.yml, .sync/workflows/leaf/release-draft.yml
Changes the way release drafter handles drafting releases on repos with release branches (which have dev branches now).
Ultimately, a release is drafted for the dev branch and the release branch. The releases are differentiated by both their release title and tag.
- Release Branch
- Title: `release-v<version>`
- Tag: `v<version>`
- Dev Branch
- Title: `dev-v<version>`
- Tag: `dev-v<version>`
Note that the tag for the release branch follows the same convention as existing release tags.
The "release branch" release includes all pull requests made to the dev branch with the `type:backport` label since the last "dev branch" release. For this reason, the "dev branch" and "release branch" should be released at the same time. Then, this effectively results in the "release branch" having all …
=> Update Release Drafter for Dev Branches

Jobs/PrGate.yml
Add artifacts_binary and artifacts_other parameters to Jobs/PrGate.yml to let consumer able to customize the binary and other path for publishing content to pipeline artifact
=> Add artifacts_binary and artifacts_other parameters to Jobs/PrGate.yml

.sync/rust_config/rust-toolchain.toml
Current automation and scripts expect the section with tools to be called "[tools]".
=> .sync/rust-toolchain.toml: Use [tools] section

.sync/Version.njk
Since `cargo-binstall` is being used to install Rust binaries, update to the latest version of `cargo-make` and `cargo-tarpaulin`.
Note: `RustSetupSteps.yml` in this repo gets updated from this version during the file sync.
=> .sync/Version.njk: Update cargo-make and cargo-tarpaulin to latest

.sync/containers/Ubuntu-22/Dockerfile, Containers/Ubuntu-22/Dockerfile
The `pythonx.x-distutils` package provided the standard `distutils` module for our Ubuntu container Python environment.
In the deadsnakes PPA python3.12.7-1+jammy1 to python3.12.8-1+jammy1 update on 12/04/2024, the following diff was made:
https://launchpadlibrarian.net/761821028/python3.12_3.12.7-1+jammy1_3.12.8-1+jammy1.diff.gz
In that, `python3.12-distutils` is no longer a built package per [PEP-0632](https://peps.python.org/pep-0632/). Therefore, it is removed from the container using Python 3.12 and some subsequent Python code updates may need to made for compatibility.
This change is specifically focused on fixing the Ubuntu 22.04 (jammy) container build.
---
Marked as a breaking change since `distutils` will no longer be installed in the container.
=> Containers/Ubuntu-22: Remove pythonx.x-distutils

.sync/Version.njk
- Updates the container to latest `af4ec63`
- This container image does not have `python3.12-distutils`
- Updates the Mu DevOps version synced from "v12.4.0" to "v12.4.2".
---
Marked as breaking change due to the container update that contains a potentially breaking change.
=> Version.njk: Update Ubuntu build container version and use Mu Devops 12.4.2

.github/workflows/Build-Containers.yml, .sync/Files.yml, .sync/containers/Ubuntu-24/Dockerfile, Containers/Readme.md, Containers/Ubuntu-24/Dockerfile
Closes #403 
Adds a new dockerfile to build a Ubuntu 24.04 image.
- https://releases.ubuntu.com/noble/
As we continue to update other Linux dependencies such as our Python installation and various packages, we can maintain better compatibility with pre-compiled binaries and get newer, safer updates by moving to the latest Ubuntu stable release.
In particular, glibc 2.39 is now included by default which allows us to move ahead to newer binaries being pulled into the build like `cargo-make` v0.37.24.
---
Ubuntu 22.04 image:
```
/.cargo/bin/cargo-make: /lib/x86_64-linux-gnu/libc.so.6: version
`GLIBC_2.39' not found (required by /.cargo/bin/cargo-make)
```
Ubuntu 24.04 image:
```
root@4d1e94a3013a:/src/mu_tiano_platforms# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu …
```
=> Add Ubuntu 24.04 (Noble Numbat) container build

.sync/containers/Ubuntu-22/Dockerfile, .sync/containers/Ubuntu-24/Dockerfile, Containers/Ubuntu-22/Dockerfile, Containers/Ubuntu-24/Dockerfile
**Ubuntu 24.04: Update iasl 20210105.0.6 to 20230628.0.1**
Updates iasl to the latest built Mu version matching the version
used in Mu ext deps.
---
**Fix Ubuntu iasl wrong machine type**
A long standing issue has been that the AARCH64 binary is copied
to /usr/bin/iasl in the x86-64 container image. This copies the
x86 binary.
---
**Before**
```
root@724459c0de48:/src/mu_tiano_platforms# readelf -h /usr/bin/iasl  
ELF Header:
Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
Class:                             ELF64
Data:                              2's complement, little endian
Version:                           1 (current)
OS/ABI:                            UNIX - System V
ABI Version:                       0
Type:                              EXEC (Executable file)
Machine: …
```
=> Update Ubuntu Container iASL [Rebase & FF]

Containers/Ubuntu-24/Dockerfile
Many of the existing CI workflows expect a pip environment to use. A new user and group are created for the docker user when the container image is initialized in pipelines. This allows that user to use the /opt/venv environment to support existing workflows.
=> Containers/Ubuntu-24: Allow CI user access to venv

.sync/Version.njk
Includes the change to allow the CI user account to use pip.
=> .sync/Version.njk: Update Ubuntu 24.04 container to d412ccd

Scripts/DownloadCargoBinaryFromGitHub/DownloadCargoBinaryFromGitHub.py
Currently, the `cargo-binstall` most recent release in the binstall repo does not actually have the binstall binary. This change allows the search to find the most recent release that has the expected binaries to handle the case when other releases might also be in release list that do not have the expected binaries.
=> DownloadCargoBinaryFromGitHub: Find most recent release with assets

.sync/Version.njk, .sync/rust_config/rust-toolchain.toml
The release GitHub workflow downloads and caches the cargo tools in the rust-toolchain.toml file so sync it.
=> .sync/rust-toolchain.toml: Sync cargo-release

Steps/BinaryCopyAndPublish.yml, Steps/OtherCopyAndPublish.yml
The Binary and Other artifact publish is depending on `artifacts_present` variable, but the variable will only be set to false or true when all previous steps are success.
In some cases, we want to always upload the artifacts no matter previous steps are pass or failed, and this `artifacts_present` already be handled well to decide the binary and other artifact should be uploaded or not, hence add the `condition: succeededOrFailed()` to the step that set the `artifacts_present` variable
=> Always update artifacts_present variable in artifact publish

.sync/Version.njk, ReadMe.rst
Update Readme.rst to contain details on process for updating rust_toolchain.
=> .sync/Version.njk: Update linux_build_container to for 1.84.0 rust toolchain.

.sync/Files.yml
This change onboards the `mu_feature_ffa` repo to be part of the mu repo collection, by synchronizing the necessary files into the repo automatically.
=> Synchronize files into `mu_feature_ffa` repo

.github/workflows/FileSyncer.yml, .sync/workflows/leaf/backport-to-release-branch.yml, .sync/workflows/leaf/submodule-release-update.yml
Generates tokens during workflow execution instead of directly depending on PATs.
=> Update non-Default GitHub token usage to Mu GitHub app

.github/workflows/FileSyncer.yml
Allow file syncer to access all repos in the owning repo's installation and use the `GH_INSTALLATION_TOKEN` parameter to provide the token as the action differentiates between PATs using `GH_PAT` and apps using `GH_INSTALLATION_TOKEN`.
=> FileSyncer.yml: Create app derived token for all repos

.sync/containers/Ubuntu-22/Dockerfile, .sync/containers/Ubuntu-24/Dockerfile
This change picks up QEMU v10 for docker images, which has a timer feature for AArch64 that is needed by hafnium build v2.13.
=> Update docker image to build QEMU v10

Notebooks/PullRequests.github-issues
Excludes `mu-automation[bot]` account PRs in the human list.
=> PullRequests.github-issues: Add mu-automation to bot list

.sync/workflows/leaf/submodule-release-update.yml
Prevents `{{` and `}}` from being interpreted as Nunjucks substitutions.
=> submodule-release-updater.yml: Treat GitHub vars as raw Nunjucks values

.sync/containers/Ubuntu-22/Dockerfile, .sync/containers/Ubuntu-24/Dockerfile, ReadMe.rst
Sync's the rust toolchain version and cargo_make / cargo_tarpaulin version from the Version.njk file instead of needing to be updated manually.
=> containers: Sync rust related versions from Version.njk

.github/workflows/Labeler.yml, .github/workflows/pull-request-formatting-validator.yml, .sync/workflows/leaf/label-issues.yml, .sync/workflows/leaf/pull-request-formatting-validator.yml
Use pull_request to not run workflow changes on PRs from forks.
---
Note: Tested on fork in this PR https://github.com/makubacki/mu_basecore/pull/99
=> Use pull_request instead of pull_request_target trigger

.sync/workflows/leaf/codeql-platform.yml, .sync/workflows/leaf/codeql.yml
Two changes for the CodeQL workflows:
---
**codeql: Use app token for API requests**
Make authenticated requests to prevent relying on the GitHub
anonymous API limit from potentially causing requests to
fail.
---
**codeql: Always download cargo make**
Temporarily always download cargo make instead of using the workflow
cache as loading from the cache has failed recently in some repos
and a root cause needs to be found for that issue.
Tracked in https://github.com/microsoft/mu_devops/issues/459
=> codeql: Use app token for API requests [Rebase & FF]

.sync/workflows/leaf/codeql-platform.yml, .sync/workflows/leaf/codeql.yml
b9c5931 moved to pull_request_target to use the GitHub app to derive auth tokens. This may not allow GitHub to have the propoer context for the changes in the PR. This goes back to pull_request. Since only read permission is needed for the token, this sets uses the default token to make authenticated API calls.
=> codeql: Go back to pull_request

.sync/dependabot/actions-pip-submodules.yml
mu_tiano_platforms added Silicon/Arm/TFA and Silicon/Arm/HAF as submodules.
Dependabot was creating PRs to update.
Add these repos to the ignore list for dependabot.
=> Add to the dependenabot ignore subrepos the TFA and HAF repos

.sync/rust_config/rustfmt.toml
Some downstream repos updated to 2024 rustfmt.
Update the synced version of rustfmt to remove specifying a format.  This way, the edition will use the repo's Cargo.toml.
=> Update rustfmt to use local repo version instead of mu_devops version.

.sync/Files.yml
mu_crypto_release is moving to a main branch. 
Update file sync to no longer sync the
=> Move crypto_release out of Dev/Release file sync

.sync/Version.njk
Updates to the latest container build with the components included for the Hafnium build.
=> Version.njk: Update Ubuntu-24 container to 71390ed

.sync/Version.njk
Step 1 to fully update the rust version to 1.85 to 1.89 as defined in [ReadMe#steps-for-updating-rust-toolchain](https://github.com/microsoft/mu_devops/?tab=readme-ov-file#steps-for-updating-rust-tool-chain).
=> Update rust version to 1.89

.sync/Version.njk
Step 4 to fully update the rust version to 1.85 to 1.89 as defined in
[ReadMe#steps-for-updating-rust-toolchain](https://github.com/microsoft/mu_devops/?tab=readme-ov-file#steps-for-updating-rust-tool-chain).
=> Update container to 737aacc

.sync/dependabot/actions-pip-submodules.yml
Add Feature/FFA to the list of submodules that dependabot should not attempt to update.
Feature/FFA should be handled though submodule updater.
=> Prevent dependabot from attempting to update Features/Ffa in mu_tiano_platforms

.sync/Version.njk
Updates Mu repos to use the latest Mu DevOps release.
=> Version.njk: Update the Mu DevOps version to v18.0.0
