microsoft/mu_devops

Jobs/PrGate.yml, Steps/PrGate.yml, Steps/SetupPythonPreReqs.yml
- Add option to specify installing tools or not
- Add option to specify container
- Only run path fix if needed
- Add work-around for pip install path
Issue #7
=> Add initial support for containers in PrGate job

Jobs/PrGate.yml, Steps/BuildPlatform.yml, Steps/SetupPythonPreReqs.yml
- Remove need for path workaround
- Add separate pip install for Linux
- Add install_tools parameter for BuildPlatform
=> Add support for platform build using containers

.github/Labels.yml, .github/workflows/CodeQl.yml, .github/workflows/FileSyncer.yml, .github/workflows/Labeler.yml, .sync/Files.yml, .sync/ReadMe.rst, .sync/azure_pipelines/Ubuntu-CLANGPDB.yml, .sync/azure_pipelines/Ubuntu-GCC5.yml, .sync/azure_pipelines/Windows-CLANGPDB.yml, .sync/azure_pipelines/Windows-VS.yml, .sync/ci_config/.markdownlint.yaml, .sync/dependabot/actions-pip-submodules.yml, .sync/dependabot/actions-pip.yml, .sync/github_templates/ISSUE_TEMPLATE/bug_report.yml, .sync/github_templates/ISSUE_TEMPLATE/config.yml, .sync/github_templates/ISSUE_TEMPLATE/documentation_request.yml, .sync/github_templates/ISSUE_TEMPLATE/feature_request.yml, .sync/github_templates/contributing/CONTRIBUTING.md, .sync/github_templates/licensing/project_mu_and_tianocore_license.txt, .sync/github_templates/licensing/project_mu_license.txt, .sync/github_templates/licensing/tianocore_license.txt, .sync/github_templates/pull_requests/pull_request_template.md, .sync/workflows/config/label-issues/file-paths.yml, .sync/workflows/config/label-issues/regex-pull-requests.yml, .sync/workflows/leaf/label-issues.yml, .sync/workflows/leaf/label-sync.yml, .sync/workflows/leaf/stale.yml, ReadMe.rst
This PR makes several changes to improve overall project operation
and efficiency across Project Mu repos.
Introduces a new directory called `.sync` that will be used to
maintain files synchronized automatically from this repo to other
repos.
The readme file in the directory explains the basics of how file
syncing works and how to configure file sync settings.
Summary:
- `.github/workflows/FileSyncer.yml` - A GitHub workflow that calls
the GitHub Action necessary to perform file syncing.
- `.sync` - A directory that contains files synced to other repos.
Note that files are mapped from this directory to the destination
file path in the file sync configuration file.
- `.sync/Files.yml` - The file sync configuration file. Defines
which files/directories are synced to which repos and maps any …
=> Update Project Mu GitHub Automation [Rebase & FF]

ReadMe.rst
Display status of file sync from this repo to Project Mu repos
in a badge at the top of the main repo readme file.
Also adds a badge with the latest Mu DevOps release version
to make the release more obvious.
=> ReadMe.rst: Add file sync status badge

.sync/Version.njk
https://github.com/microsoft/mu_devops/compare/v0.1.0...v1.1.1
General release info:
https://github.com/microsoft/mu_devops/releases
=> .sync/Version.njk: Update Mu repos to Mu DevOps v1.1.1

.sync/azure_pipelines/custom/mu_feature_config/Ubuntu-GCC5.yml
Fixes an incorrect change that resulted in an invalid pipeline file.
=> Fix incorrect changes to mu_feature_config custom Ubuntu-GCC5 pipeline

.sync/Version.njk
https://github.com/microsoft/mu_devops/compare/v1.1.1...v1.3.0
General release info:
https://github.com/microsoft/mu_devops/releases
=> .sync/Version.njk: Update Mu repos to Mu DevOps v1.3.0

.sync/Files.yml
Adds the auto approval workflow to the file sync list.
=> .sync/Files.yml: Sync auto approver workflow

.sync/github_templates/pull_requests/pull_request_template.md
The pull request template has a number of items contributors can
check to classify their changes. This commit updates the template
to give more details about the types of changes that impact the
checkboxes along with some examples.
=> Elaborate on check list items in PR template

.sync/Version.njk
https://github.com/microsoft/mu_devops/compare/v1.4.2...v1.7.4
General release Info: https://github.com/microsoft/mu_devops/releases
=> .sync/Version.njk: Update Mu repos to Mu DevOps v1.7.4

.sync/Files.yml, .sync/workflows/leaf/pull-request-formatting-validator.yml, ReadMe.rst
Adds a new workflow to validate pull request formatting.
=> .sync/workflows/leaf: Add PR formatting validator workflow

.sync/Version.njk
https://github.com/microsoft/mu_devops/compare/v2.0.1...v2.2.0
=> .sync/Version.njk: Update Mu repos to Mu DevOps v2.2.0

.sync/Version.njk
https://github.com/microsoft/mu_devops/compare/v2.2.0...v2.3.0
=> .sync/Version.njk: Update Mu repos to Mu DevOps v2.3.0

.sync/Version.njk
https://github.com/microsoft/mu_devops/compare/v2.4.0...v2.5.1
=> .sync/Version.njk: Update Mu repos to Mu DevOps v2.5.1

ReadMe.rst
1. Add a Table of Contents
2. Update Conventions section
3. Add a Containers section
4. Add missing workflow sections
5. Sort workflow sections so they're easier to find in the Table of Contents
6. Other minor miscellaneous updates
=> Readme.rst: Reorganize and refresh content

.sync/azure_pipelines/MuDevOpsWrapper.yml
Update the relative path for the proper number of parent directories.
=> .sync/azure_pipelines/MuDevOpsWrapper.yml: Fix Version.njk path

.sync/Version.njk, Jobs/PrGate.yml
1. Updates the container to include container fix for azure pipeline path
2. Removes the path work-around from the pipeline files
=> Remove the azure user path work-around.

Containers/Ubuntu-22/Dockerfile
Adds missing alternatives for the cpp tool which is used when building TF-A.
=> Add CPP alternative to ubuntu container.

.sync/Version.njk
https://github.com/microsoft/mu_devops/compare/v6.0.0...v6.1.0
=> .sync/Version.njk: Update Mu repos to Mu DevOps v6.1.0

.sync/Files.yml, Notebooks/MyPullRequests.github-issues, Notebooks/OpenIssues.github-issues, Notebooks/PullRequests.github-issues
Adds the mu_rust_hid repo as a file sync target for relevant files.
=> .sync/Files.yml: Sync files to mu_rust_hid [Rebase & FF]

.sync/Version.njk
https://github.com/microsoft/mu_devops/compare/v6.1.0...v6.4.1
=> .sync/Version.njk: Update Mu repos to Mu DevOps v6.4.1

.sync/azure_pipelines/MuDevOpsWrapper.yml, Steps/RustCargoSteps.yml
Sets the parameter to true since this usage of the template is always using a container.
=> MuDevOpsWrapper.yml: Set container_build parameter

.sync/Version.njk
https://github.com/microsoft/mu_devops/compare/v6.4.1...v6.5.1
=> .sync/Version.njk: Update Mu repos to Mu DevOps v6.5.1

.sync/Version.njk, Steps/RustSetupSteps.yml
Updates to the latest Rust version currently available to allow code
to use the latest features.
https://blog.rust-lang.org/2023/10/05/Rust-1.73.0.html
=> .sync/Version.njk: Update to Rust 1.73.0

.sync/Version.njk, Jobs/PrGate.yml
Updates the Code coverage command to also use the following flags:
CC_FLATTEN=TRUE - de-duplicates source file coverage due to the same source file being used by multiple INFs.
CC_FULL=TRUE - inserts coverage data (correct code line count, but zero lines covered) for all source files in the package that are not present in the original coverage report.
Pipelines consuming this change must add pygount to their pip-requirements file.
=> Jobs/PrGate.yml: Update Code Coverage commands

.github/workflows/pull-request-formatting-validator.yml, .sync/workflows/leaf/pull-request-formatting-validator.yml
Ensure that the latest version of the action is synced to other repos (v7).
=> pull-request-formatting-validator: Use github-script v7

Notebooks/MyPullRequests.github-issues, Notebooks/OpenIssues.github-issues, Notebooks/PullRequests.github-issues
Adding secureboot_objects repo to the queries for issues and pull requests.
=> Add secureboot objects repo to notebook queries

.sync/workflows/leaf/codeql-platform.yml, .sync/workflows/leaf/codeql.yml
Matches the latest version being propagated by dependabot.
=> .sync/workflows/codeql: Update sync action to v4

.sync/Version.njk, Steps/RustSetupSteps.yml
Routine update to keep current.
=> .sync/Version.njk: Update to Rust 1.74

.sync/Version.njk
Updates mu_devops to 9.1.8 to take use the most recent rustup changes.
=> Update mu_devops to 9.1.8

Jobs/PrGate.yml
Fix a string comparation expression issue in /Jobs/PrGate.yml
=> Jobs/PrGate.yml: Fix 'CLANGPDB' string expression issue

Steps/InstallMarkdownLint.yml, Steps/InstallSpellCheck.yml, Steps/PrGate.yml
Add "extra_npm_args" for InstallMarkdownLint.yml and InstallSpellCheck.yml steps to increase the flexibility to npm actions.
=> Add extra_npm_args for InstallMarkdownLink.yml and InstallSpellCheck

.sync/github_templates/contributing/CONTRIBUTING.md, .sync/github_templates/pull_requests/pull_request_template.md
Remove redundant `"to complete"` from PR template
=> Minor fix to PR template

.sync/workflows/leaf/codeql-platform.yml, .sync/workflows/leaf/codeql.yml
Updates `codeql.yml` and `codeql-platform.yml` to run on dev/* branches.
=> .sync: Update codeql to run on dev/* branches

.github/workflows/Build-Containers.yml
Builds the container on a change to the version file.
=> Build-Containers.yml: Trigger on Version.njk change

.sync/Version.njk
See the following comparison for details of the changes
between these releases:
https://github.com/microsoft/mu_devops/compare/v10.0.0...v12.0.2
=> .sync/Version.njk: Update to Mu DevOps v12.0.2

.sync/Version.njk
See the following comparison for details of the changes between these releases:
https://github.com/microsoft/mu_devops/compare/v12.2.0...v12.4.0
=> .sync/Version.njk: Update to Mu DevOps v12.4.0

.github/actions/rust-tool-cache/action.yml, .github/workflows/ReleaseWorkflow.yml, .sync/Files.yml, .sync/workflows/leaf/publish-release.yml
Publishes crates in Rust repos to the repo designated registry (crates.io default).
=> Add crate release workflow

.sync/Version.njk
See the following comparison for details of the changes between these
releases:
https://github.com/microsoft/mu_devops/compare/v13.0.0...v13.0.3
=> .sync/Version.njk: Update mu_devops to v13.0.3

.sync/Files.yml
Add pull request template as file synced to secureboot_objects.
=> Add secureboot_objects to repos which pull_request_template is synced.

.sync/workflows/leaf/codeql-platform.yml, .sync/workflows/leaf/codeql.yml
Use the latest version in CodeQL workflows.
=> .sync/codeql: Update robinraju/release-downloader to v1.12

.sync/Version.njk, .sync/workflows/leaf/backport-to-release-branch.yml
Switch n,n-1 to 202502, 202405
=> Version.njk Update to 202502, 202405 versions

.sync/Version.njk
The new container incorporates QEMU v10.0.0 to support hafnium v2.13.
=> Update container version to 4d8e1b7 to use QEMU 10

.sync/Version.njk
Updates the rust version to 1.85.0
=> Update rust to 1.85.0

.sync/Version.njk
Need a 15.0.1 release so that the syncer will update all MuDevopsWrapper.yml to 15.0.1
=> Update Version.njk to prepare for 15.0.1 release

.sync/Version.njk
Includes:
- codeql: Use app token for API requests
- Use the GitHub app token for writing
---
Bumps the version for an upcoming release.
=> Update Mu DevOps version to 15.0.3

.sync/Version.njk
Updates Mu repos to use the latest Mu DevOps release.
=> Version.njk: Update the Mu DevOps version to v16.0.0
